TEXT = {
    "app_title": "PII Log Cleaner",
    "version": "v1.0.4",
    "select_target": "1. 대상 선택",
    "select_folder": "폴더 선택",
    "select_files": "파일 선택",
    "add_files": "+ 파일 추가",
    "remove_selected": "− 선택 제거",
    "remove_all": "전체 제거",
    "selected_files": "선택된 파일 수: {count}개",
    "supported_formats": "* 지원 형식: .log, .txt, .out, .csv, .sql",
    "drag_drop_hint": "파일 또는 폴더를 목록으로 끌어 놓을 수 있습니다.",
    "file_path": "파일 경로",
    "size": "크기",
    "modified": "수정한 날짜",
    "remove": "제거",
    "detect_items": "2. 탐지 항목 선택",
    "masking": "3. 치환 방법",
    "options": "4. 기타 옵션",
    "preview": "5. 미리보기 (최대 100건)",
    "auto": "자동 변경 (권장)",
    "auto_detail": "항목별 자동 토큰으로 변경\n(예: [PERSON_1], [PHONE_1])",
    "custom": "지정 문자열로 변경",
    "custom_detail": "모든 항목을 지정한 문자열로 변경",
    "custom_placeholder": "치환할 문자열 입력",
    "partial": "부분 마스킹",
    "partial_detail": "일부만 보이고 나머지 마스킹\n(예: 010-****-5678)",
    "partial_style": "전화번호 마스킹 형태",
    "backup": "원본 파일 백업",
    "backup_detail": "비식별화 전 원본 파일을 .bak 폴더에 복사",
    "report": "결과 리포트 생성",
    "report_detail": "탐지 결과를 CSV로 저장",
    "large_file": "대용량 파일 최적화 모드",
    "large_file_detail": "메모리 사용을 최소화하여 처리 (권장)",
    "encoding": "인코딩 자동 감지",
    "encoding_detail": "UTF-8, EUC-KR, CP949 등 자동 감지",
    "recursive": "하위 폴더 포함",
    "recursive_detail": "선택한 폴더의 하위 폴더까지 처리",
    "start_analysis": "분석 시작",
    "run_deid": "비식별화 실행",
    "stop": "중지",
    "summary": "실행 요약",
    "summary_item": "항목",
    "summary_value": "내용",
    "summary_file_count": "총 파일 수",
    "summary_detection_count": "탐지 항목 수",
    "summary_replacement_count": "치환 수",
    "summary_duration": "처리 시간",
    "summary_started": "시작 시간",
    "summary_finished": "완료 시간",
    "history": "최근 실행 히스토리",
    "view_all": "전체 보기 ›",
    "history_time": "실행 시간",
    "history_target": "대상 경로",
    "history_status": "상태",
    "complete": "완료",
    "cancelled": "중지됨",
    "original": "원본 로그",
    "deidentified": "비식별화 결과 (미리보기)",
    "found": "탐지 항목",
    "preview_note": "* 미리보기는 일부 데이터만 표시됩니다.",
    "view_full_preview": "전체 미리보기",
    "ready": "준비 완료",
    "preparing": "준비 중…",
    "no_files": "처리할 파일을 선택해주세요.",
    "no_analysis": "먼저 분석을 완료해주세요.",
    "custom_required": "치환할 문자열을 입력해주세요.",
    "model_error": "개인정보 탐지 엔진을 초기화하지 못했습니다.\n프로그램을 다시 설치해주세요.",
    "encoding_error": "인코딩을 자동으로 확인하지 못했습니다.",
    "permission_error": "파일을 읽을 권한이 없습니다.",
    "in_use_error": "파일이 다른 프로그램에서 사용 중입니다.",
    "space_error": "결과 파일을 저장할 공간이 부족합니다.",
    "nothing_found": "선택 가능한 지원 파일이 없습니다.",
    "duplicates_skipped": "이미 추가된 파일 {count}개를 제외했습니다.",
    "files_added": "파일 {count}개를 추가했습니다.",
    "processing": "처리 중: {current}/{total}",
    "analysis_complete": "분석이 완료되었습니다.",
    "deid_complete": "비식별화 파일을 생성했습니다.",
}
